### ISSUE TITLE
Uncaught TypeError: $(...).geocomplete is not a function on AWS

### ISSUE THREAD

**Issue by anwain** [jshimko/meteor-geocomplete#20] opened 2015-11-20 10:45 UTC
Hey, I get this when using mupx and AWS but not when working locally
Uncaught TypeError: $(...).geocomplete is not a function

Any ideas?

**Comment by jshimko** [comment] 2015-11-20 12:33
Pretty hard to tell without more information.  If you can put up a reproduction repo, I'd be happy to take a look at it.

**Comment by jshimko** [comment] 2015-11-25 19:12
Since this isn't an issue anyone else appears to be having, it seems it's on your end.  I'm going to close this issue for now.  Feel free to reopen if you determine there's something wrong with this package.

Thanks!

**Closed as completed by jshimko** 2015-11-25 19:12 UTC

**Comment by anwain** [comment] 2015-11-25 21:33
Sorry for not following up. Can't share the codebase just yet, will figure it out though and let you know, thanks

**Comment by jshimko** [comment] 2015-11-25 21:40
You don't necessarily need to share your app.  You could clone my [demo repo for the geocomplete package](https://github.com/jshimko/meteor-geocomplete-example) and try using that to reproduce the issue.  That might at least get you closer to figuring out what's causing it.

Good luck!
